# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hcg/hcg/visual_navigation/visnav_new

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hcg/hcg/visual_navigation/visnav_new

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hcg/hcg/visual_navigation/visnav_new/CMakeFiles /home/hcg/hcg/visual_navigation/visnav_new/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hcg/hcg/visual_navigation/visnav_new/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named calibration

# Build rule for target.
calibration: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 calibration
.PHONY : calibration

# fast build rule for target.
calibration/fast:
	$(MAKE) -f CMakeFiles/calibration.dir/build.make CMakeFiles/calibration.dir/build
.PHONY : calibration/fast

#=============================================================================
# Target rules for targets named test_ceres_se3

# Build rule for target.
test_ceres_se3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_ceres_se3
.PHONY : test_ceres_se3

# fast build rule for target.
test_ceres_se3/fast:
	$(MAKE) -f CMakeFiles/test_ceres_se3.dir/build.make CMakeFiles/test_ceres_se3.dir/build
.PHONY : test_ceres_se3/fast

#=============================================================================
# Target rules for targets named odometry

# Build rule for target.
odometry: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 odometry
.PHONY : odometry

# fast build rule for target.
odometry/fast:
	$(MAKE) -f CMakeFiles/odometry.dir/build.make CMakeFiles/odometry.dir/build
.PHONY : odometry/fast

#=============================================================================
# Target rules for targets named sfm

# Build rule for target.
sfm: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sfm
.PHONY : sfm

# fast build rule for target.
sfm/fast:
	$(MAKE) -f CMakeFiles/sfm.dir/build.make CMakeFiles/sfm.dir/build
.PHONY : sfm/fast

#=============================================================================
# Target rules for targets named test_ex4

# Build rule for target.
test_ex4: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_ex4
.PHONY : test_ex4

# fast build rule for target.
test_ex4/fast:
	$(MAKE) -f test/CMakeFiles/test_ex4.dir/build.make test/CMakeFiles/test_ex4.dir/build
.PHONY : test_ex4/fast

#=============================================================================
# Target rules for targets named test_ex3

# Build rule for target.
test_ex3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_ex3
.PHONY : test_ex3

# fast build rule for target.
test_ex3/fast:
	$(MAKE) -f test/CMakeFiles/test_ex3.dir/build.make test/CMakeFiles/test_ex3.dir/build
.PHONY : test_ex3/fast

#=============================================================================
# Target rules for targets named test_ex5

# Build rule for target.
test_ex5: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_ex5
.PHONY : test_ex5

# fast build rule for target.
test_ex5/fast:
	$(MAKE) -f test/CMakeFiles/test_ex5.dir/build.make test/CMakeFiles/test_ex5.dir/build
.PHONY : test_ex5/fast

#=============================================================================
# Target rules for targets named test_ex2

# Build rule for target.
test_ex2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_ex2
.PHONY : test_ex2

# fast build rule for target.
test_ex2/fast:
	$(MAKE) -f test/CMakeFiles/test_ex2.dir/build.make test/CMakeFiles/test_ex2.dir/build
.PHONY : test_ex2/fast

#=============================================================================
# Target rules for targets named test_ex0

# Build rule for target.
test_ex0: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_ex0
.PHONY : test_ex0

# fast build rule for target.
test_ex0/fast:
	$(MAKE) -f test/CMakeFiles/test_ex0.dir/build.make test/CMakeFiles/test_ex0.dir/build
.PHONY : test_ex0/fast

#=============================================================================
# Target rules for targets named test_ex1

# Build rule for target.
test_ex1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_ex1
.PHONY : test_ex1

# fast build rule for target.
test_ex1/fast:
	$(MAKE) -f test/CMakeFiles/test_ex1.dir/build.make test/CMakeFiles/test_ex1.dir/build
.PHONY : test_ex1/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) -f test/googletest/googlemock/CMakeFiles/gmock_main.dir/build.make test/googletest/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) -f test/googletest/googlemock/CMakeFiles/gmock.dir/build.make test/googletest/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) -f test/googletest/googlemock/gtest/CMakeFiles/gtest_main.dir/build.make test/googletest/googlemock/gtest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) -f test/googletest/googlemock/gtest/CMakeFiles/gtest.dir/build.make test/googletest/googlemock/gtest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

src/calibration.o: src/calibration.cpp.o

.PHONY : src/calibration.o

# target to build an object file
src/calibration.cpp.o:
	$(MAKE) -f CMakeFiles/calibration.dir/build.make CMakeFiles/calibration.dir/src/calibration.cpp.o
.PHONY : src/calibration.cpp.o

src/calibration.i: src/calibration.cpp.i

.PHONY : src/calibration.i

# target to preprocess a source file
src/calibration.cpp.i:
	$(MAKE) -f CMakeFiles/calibration.dir/build.make CMakeFiles/calibration.dir/src/calibration.cpp.i
.PHONY : src/calibration.cpp.i

src/calibration.s: src/calibration.cpp.s

.PHONY : src/calibration.s

# target to generate assembly for a file
src/calibration.cpp.s:
	$(MAKE) -f CMakeFiles/calibration.dir/build.make CMakeFiles/calibration.dir/src/calibration.cpp.s
.PHONY : src/calibration.cpp.s

src/odometry.o: src/odometry.cpp.o

.PHONY : src/odometry.o

# target to build an object file
src/odometry.cpp.o:
	$(MAKE) -f CMakeFiles/odometry.dir/build.make CMakeFiles/odometry.dir/src/odometry.cpp.o
.PHONY : src/odometry.cpp.o

src/odometry.i: src/odometry.cpp.i

.PHONY : src/odometry.i

# target to preprocess a source file
src/odometry.cpp.i:
	$(MAKE) -f CMakeFiles/odometry.dir/build.make CMakeFiles/odometry.dir/src/odometry.cpp.i
.PHONY : src/odometry.cpp.i

src/odometry.s: src/odometry.cpp.s

.PHONY : src/odometry.s

# target to generate assembly for a file
src/odometry.cpp.s:
	$(MAKE) -f CMakeFiles/odometry.dir/build.make CMakeFiles/odometry.dir/src/odometry.cpp.s
.PHONY : src/odometry.cpp.s

src/sfm.o: src/sfm.cpp.o

.PHONY : src/sfm.o

# target to build an object file
src/sfm.cpp.o:
	$(MAKE) -f CMakeFiles/sfm.dir/build.make CMakeFiles/sfm.dir/src/sfm.cpp.o
.PHONY : src/sfm.cpp.o

src/sfm.i: src/sfm.cpp.i

.PHONY : src/sfm.i

# target to preprocess a source file
src/sfm.cpp.i:
	$(MAKE) -f CMakeFiles/sfm.dir/build.make CMakeFiles/sfm.dir/src/sfm.cpp.i
.PHONY : src/sfm.cpp.i

src/sfm.s: src/sfm.cpp.s

.PHONY : src/sfm.s

# target to generate assembly for a file
src/sfm.cpp.s:
	$(MAKE) -f CMakeFiles/sfm.dir/build.make CMakeFiles/sfm.dir/src/sfm.cpp.s
.PHONY : src/sfm.cpp.s

src/test_ceres_se3.o: src/test_ceres_se3.cpp.o

.PHONY : src/test_ceres_se3.o

# target to build an object file
src/test_ceres_se3.cpp.o:
	$(MAKE) -f CMakeFiles/test_ceres_se3.dir/build.make CMakeFiles/test_ceres_se3.dir/src/test_ceres_se3.cpp.o
.PHONY : src/test_ceres_se3.cpp.o

src/test_ceres_se3.i: src/test_ceres_se3.cpp.i

.PHONY : src/test_ceres_se3.i

# target to preprocess a source file
src/test_ceres_se3.cpp.i:
	$(MAKE) -f CMakeFiles/test_ceres_se3.dir/build.make CMakeFiles/test_ceres_se3.dir/src/test_ceres_se3.cpp.i
.PHONY : src/test_ceres_se3.cpp.i

src/test_ceres_se3.s: src/test_ceres_se3.cpp.s

.PHONY : src/test_ceres_se3.s

# target to generate assembly for a file
src/test_ceres_se3.cpp.s:
	$(MAKE) -f CMakeFiles/test_ceres_se3.dir/build.make CMakeFiles/test_ceres_se3.dir/src/test_ceres_se3.cpp.s
.PHONY : src/test_ceres_se3.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... calibration"
	@echo "... test_ceres_se3"
	@echo "... odometry"
	@echo "... sfm"
	@echo "... test"
	@echo "... test_ex4"
	@echo "... test_ex3"
	@echo "... test_ex5"
	@echo "... test_ex2"
	@echo "... test_ex0"
	@echo "... test_ex1"
	@echo "... gmock_main"
	@echo "... gmock"
	@echo "... gtest_main"
	@echo "... gtest"
	@echo "... src/calibration.o"
	@echo "... src/calibration.i"
	@echo "... src/calibration.s"
	@echo "... src/odometry.o"
	@echo "... src/odometry.i"
	@echo "... src/odometry.s"
	@echo "... src/sfm.o"
	@echo "... src/sfm.i"
	@echo "... src/sfm.s"
	@echo "... src/test_ceres_se3.o"
	@echo "... src/test_ceres_se3.i"
	@echo "... src/test_ceres_se3.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

